export {
  createScorer,
  isMatch,
  scoreIfMatch,
  type CustomScorerConfiguration,
  type Direction,
  type MaybeSequence,
  type Metric,
  type Scorer,
  type Sequence,
  type ThresholdOptions,
} from './scorer.js'
export {
  bestMatch,
  createMatcher,
  scoreMatrix,
  scorePairs,
  search,
  type BestOptions,
  type Items,
  type Match,
  type Matcher,
  type MatcherOptions,
  type MatrixOptions,
  type MissingItemsPolicy,
  type Normalizer,
  type ScoreArray,
  type ScoreArrayKind,
  type ScoreArrayOf,
  type ScoreMatrix,
  type SearchOptions,
} from './operations.js'
export { normalizeText } from './utils.js'
